hideable.json
- hideable.json: Make all entries the same 1-line format
- hideable.json: add "Left Col: Buy and Sell Groups"
- hideable.json: add "Left Col: Marketplace"
- hideable.json: add "Left Col: Shops"
- hideable.json: add "Left Col: News Feed"
- hideable.json: add "Left Col: Messages"
REVIEW NOTES:
1. This has the same contents as the other one, except format.  You choose.
2. I expect "News Feed" and "Messages" were intentionally left out.  If this was because you didn't see why anyone would delete them: neither do I, necessarily, but it's their screen, let them munge it as desired.  OTOH if it was because you thought FB might object: hmm, that seems vaguely possible, but it isn't like we're actually blocking anyone from accessing those things.  Just removing Yet Another Multiply Redundant Route …
=> RECOMMENDED: hideable.json: choose 1-line format, add 5 more left col entries

filters.json
- Remove false-matching selector "img[src*=\"facebook.com%2Fads%2Fimage%2F\"]"
- Match "action" strings against the right field and add "Suggested Game"
=> Remove false match, improve action match of Sponsored filter

tweaks.json
_Note: under test at [facebook.com/1283271201757627](https://facebook.com/1283271201757627)_
- Make it work on 'shared' posts
- Globally change ".userContent" to ".fbUserContent [data-ft]"
- Make it more likely to survive minor FB HTML structure changes:
- Use "[role="presentation"]" to distinguish the text copy we want
- Use ":not([role="presentation"])" to distinguish the one we don't
- Make it more compatible with "themes" a user might have installed:
- "color:inherit" rather than "color:black"
- "font-weight:inherit" rather than "font-weight:normal"
- Remove "position:static", which made such posts act oddly, e.g.
couldn't click the timestamp permalink
=> "Remove Status Background Colors" improvements:

tweaks.json
.userContent has gone back to .fbUserContent for me.
We don't need a specific reference to either; `[data-ft] > *[style*="background-"]` is unique.  For robustness, wrap in [sfx_post] so we only affect what we've recognized as a post.
github says in red "Can't automatically merge", yet seemed to think my local repository was identical to upstream/master when I branched off this small commit... also says "don't worry, you can still create the pull request" so I'm going ahead to see what happens...
=> Make "Remove Status Background Colors" less sensitive to post structure

filters.json
- change to case-sensitive matching to minimize false matches
- add ' likes ', as seen in https://facebook.com/1310697838999094
- parenthesize the whole expression with (.* .*) so that the whole 'Action' is captured
- provide "show_note: true" and "custom_note: $1" so that if the user changes action from 'move-to-tab' to 'hide', it magically displays the action field
- includes "updated_on" field (please check that this does not interact negatively with the subscription service?)
- WARNING WARNING WARNING -- I have tested this in SFx myself, but am hand-editing the JSON here and have not done end-to-end testing that it still works when injected into the subscription stream!  Please verify!
=> add 'likes' to Friend Activity Stories (+ other refinements)

filters.json
- Use the 'center-dot' endpoint to anchor the search
- 180 chars from beginning has caught every one I've seen for 2 days
- 'matches' rather than 'contains', to make it a case-sensitive search
- Should be nearly proof against false matches
- Breaks instantly if FB change that separator char; that's what the subscription model is for...
See https://facebook.com/1241563505928397 for current in-progress discussion about fixing this.  "Sponsored filter isn't working" is our #1 FAQ right now.
BTW, at least some of the CSS-based filtering is still working -- I have those elements circled by a CSS tweak and they are circled on most of the filtered posts.
I do believe something should be done to how 'Action' is scraped, so that it pulls all text before the timestamp.  But this is more immediate …
=> Supply a currently working 'Sponsored / Suggested' filter:

hideable.json
- hideable.json: "Group: Learn About This Group"
- hideable.json: "Post: Products Shown" (note, this is an element of a post, e.g. facebook.com/2069271356637380)
- hideable.json: "Left Col: Watch"
- hideable.json: "Left Col: Safety Check"
Pics for three of these -- I don't have a pic of 'Learn About This Group' at the moment...
=> 2017-08-30 hideables

filters.json
Unfortunately this has to resort to the ugly internal ._#$% selectors.  But it works.
I retained but coalesced the older selectors.  Note that none of them are working for *me*; but since FB pushes different junk to every user, I can't be certain.  I would support pushing a version completely lacking the ".uiStreamSponsoredLink,..." multi-selector *if* you were standing ready, hair-trigger, to put them back if users started complaining...
=> - filters.json: currently effective selectors for Sponsored/Suggested

filters.json
This catches sponsored posts of the 'advertiser shared [advertiser's] post' form, where the inner post has a timestamp but the outer still doesn't.
=> - filters.json: use ._5u5j to focus the primary container

hideable.json
- hideable.json: add '(RECOMMEND: HIDE INDIVIDUAL ITEMS)' to title of old 'Right Col: Reminders'
- hideable.json: add 'Right Col: Reminders: Events'
- hideable.json: add 'Right Col: Reminders: Birthdays'
- hideable.json: add 'Right Col: Reminders: Games'
- hideable.json: add 'Right Col: Reminders: Ticker Toggle' (probably obsolete)
- hideable.json: add 'Post: Add a Donate Button'
- hideable.json: add 'Page: Friends and (name of page)'
=> New hiders for Reminder types; Donate Button importunity; 'Page: Friends and (name of page)'

hideable.json
not hide 'Blocked', 'Unavailable', and a bunch of other stuff on
the members page (facebook.com/groups/_name_of_group_/members)
=> - hideable.json: redefine 'Right Col: Suggested Groups' so it does

hideable.json
it works equally on the group page (normal 'posts' mode) as on
the members page (facebook.com/groups/_name_of_group_/members)
=> - hideable.json: again redefine 'Right Col: Suggested Groups' so

hideable.json
(this leaves the 'Add Members' header visible: it has no selectable
characteristics; so live with it.  Old string hides headings like
'Groups', 'Pages' on facebook.com/search/top/?q=social+fixer)
=> - hideable.json: 'Group Right Col: Add Members' don't hide lots of unrelated headers

hideable.json
- hideable.json: split (remove) 'Far Right Col: Instant Games / Games Your Friends Play'
- hideable.json: add 'Far Right Col: Instant Games'
- hideable.json: add 'Far Right Col: Games Your Friends Play'
Current shipping SFx code poorly handles a hideable selector which
matches two elements.
=> Fix 'Far Right Col: Instant Games / Games Your Friends Play':

filters.json
It needs to be modified to match 'commented on this' but NOT
'(.*) commented on this. \1', i.e. person commenting on their
own post, as the combination of new improved envelope scraper +
FB enveloping almost all posts with comment wrappers causes it
to eliminate more than half of all posts.
This is a temporary measure until I can spend the time to figure
out the right way to craft that regex.
=> filters.json: temporarily disable 'commented on this' in 'Friend Activity'

filters.json
This uses a negative lookahead regular expression, which I always have
terrible trouble with.  This seems to do the job, but -- will have to
see what users report.
It is specifically excluding 'Foo commented on this. Foo '; where the
precise construction of this with 'period space \1 space $' is an
artifact of how SFx constructs the 'Action' string from the text of
FB's HTML.  This is inherently fragile on several levels and will
likely require revisiting in response to various FB changes.  I
wouldn't be surprised to find it's *currently* broken by things like
'Foo commented on this. Foo shared his first post to the group Bar '.
Generally excluding 'Foo commented on this. .*Foo.*' would 'fix' that,
but there would be false matches, especially if 'Foo' is a one-word
name and others have …
=> filters.json: make 'commented on this' not apply to self-comments

filters.json
Hmmm, I committed this locally and pushed, now having second thoughts:
Currently 'Friend Activity' does not specifically filter out 'shared' stuff.  Perhaps it should; but then I think it might filter out almost everything.  But to fulfill the 'which they didn't actually create' description clause, it really should.
In which case this patch is actually counter-productive.  It was in response to someone wishing that Person A commenting on their own post wouldn't be filtered -- which I did with the previous patch, regarding only posts initiated by Person A.  True 'status' posts.
This patch does make it more self-consistent by allowing through A's comments on A's share, as well as A's initial share.
Probably best solution is: yes put this patch in; and supply a second filter which filters …
=> filters.json: 'Friend Activity' pass Person A's comments on Person A's 'share' posts

filters.json, hideable.json
Unfortunately this is another one where the hider is offset from the item.  But it does work.
I've been poking around trying to figure out the offsetting problem.  So far no joy, but I expect I'll get there and eventually a later version of SFx will correctly emplace all of the offset ones, without requiring change to hideable.json.  Providing the capability now -- despite the potential for confusion.
=> hideable.json: add 259 'Blue Bar: Create'

tweaks.json
See [facebook.com/1855138757904199](https://facebook.com/1855138757904199) for discussion & links.
I will merge this in about a day if no objections.  It will re-activate the feature for people who didn't already disable or remove the subscription tweak; we'll need to post an announcement that it's back, for people who did.
Example original post:
Appearance with previous 'Remove Status Background Colors' tweak after recent FB HTML change:
Appearance with updated tweak:
=> tweaks.json: re-enable and fix 'Remove Status Background Colors'

filters.json
What used to be '\<a href="/onthisday/?source=shared_feed_story">' is now '\<a href="/onthisday/?source=shared_feed_story&three_miles_of_gibberish">'.  Trying to make it more resilient.
I don't want to just match '/onthisday/' as users might inject such a link in a discussion about FB behavior; or it might be a completely unrelated link to some other web page which just happens to use that simple phrase in its URL.
=> filters.json: update 'Hide "Shared Memories"' to match current FB HTML

filters.json
filters.json: update 23 'Sponsored (Experimental)' with 2018-09-09 ver (part A)
filters.json: add 25 'Sponsored (Experimental) part B'
filters.json: remove spurious 'enabled', 'disabled', 'updated_on', 'content'
I'll merge this probably around 12 hours from now.
Then will promote it to 'not experimental' after a couple of days of user experience.
=> Update Sponsored/Suggested 'Experimental' filters for user test

filters.json
filters.json: make 23 'Sponsored (Experimental)' a single filter again
filters.json: add a new powerful expression to 23 'Sponsored (Experimental)'
filters.json: order 23's expressions most-to-least successful
Besides improving ad filtering, hopefully this will get by the github
pages build process.  It emailed me that the build failed, with no
details, and I couldn't find them on github.com either; attempting to
build locally with 'Jekyll' failed utterly.  But I think it was
something about the quoting of '\b', and that's gone now.
=> More work on 'Sponsored (Experimental)'

filters.json
This tags the 'Like Page' button in Sponsored posts but nothing else,
AFAICT.  It will break soon, but it's effective right now.
=> filters.json: add '._42b7' expression to 25 'Sponsored (Experimental)'

filters.json
- add three new expressions (details below)
- update the names so people will clearly see they've been updated
- these are stopgap measures until a new SFx release can be gotten out
- waiting on PR#137 :hid-within() to be committed
This adds the following CSS matches to the previous (2018-09-15) 'part A' filter:
(1) s a[role='link'] span:contains(^.$)
This matches most Sponsored posts, catching the 'S' of 'SpSonSsoSred'.
The intermingled 'S'es are individual spans.  In other languages they
are the first letter of that language's word for 'Sponsored', so should
still match (not sure what happens if that 'letter' is some sort of
non-ASCII UNICODE).  BUT, this relies on the entire 'Sponsored' block
being inside an \<s> tag, which is surely a bug they will soon correct.
Regular posts have the …
=> filters.json: 2018-09-29 edition of 23 & 25 'Sponsored (Experimental)' parts A & B

filters.json
Remove yesterday's 3rd selector, which recognizes boxes like 'Shop Now'
or 'Get Offer'.  While extremely effective, it has been shown to catch
non-sponsored posts by Pages one is following, if they have one of those
boxes.  The 1st selector is holding effective for now.
=> filters.json: 2018-09-30 edition of 'Sponsored (Experimental)', omit overeager selector

filters.json
Remove the 'Paid' selector as it triggers on such posts forwarded
(shared) by a friend, which may contain comments or discussion.  If we
had a way to express 'only try this filter on posts NOT from a friend or
a Page which I follow', it would be fine.  Some day.
Protect 'part B' against Pages the user is following.  The filter now
means 'if the post is from a Page _which I do not follow_, and Post
Action says someone likes something' -- i.e. a non-subscribed Page post
which FB has inserted with the excuse that my friends like that Page.
=> filters.json: 2018-10-02 edition of 23 & 25 'Sponsored (Experimental)' parts A & B

hideable.json
- hideable.json: make 244 'Instant Games' cover all related type of game
block (they all look the same anyway)
- hideable.json: retire 245 'Games Your Friends Play', a subtype of
'Instant Games'.  Needs to be retired as otherwise two hiders would
select the same element, with I'm not sure what consequences
=> improve 'Instant Games' hiders

filters.json
Image is of my 'Sponsored' tab, with 'Show posts marked Read' enabled -- 4 posts are unread, 3 are read (bottom border of last one is missing for some reason...)
=> hideable.json: 26 'Sponsored part C' show poster name in hidden-post msgs

filters.json
Tiny tweak... recommend 'C' first, so if same post would be caught by others, they get the benefit of seeing the Page name.
=> hideable.json: 26 'Sponsored part C' improve ordering advice

filters.json
filters.json: replace filter 26 'Sponsored C' with 'Sponsored D'
filters.json: create filter 27 'Sponsored C'
'C' is highly effective for people still receiving old format
posts.  People receiving newer formats find that it filters out
all Page posts, even from Pages they subscribe to.
'D' will be somewhat less effective, but should catch no (or
only a few) wanted Page posts.
Current 'C' subscribers will have their subscription change to
'D'.  They can optionally turn 'C' back on by subscribing to it
again.
=> push working Sponsored filter to subscribers

hideable.json
-- specifically because this cannot be filtered out
of the SFx groups, as we disable filtering there!
=> hideable.json: add 302 'News Feed: Discover Members'

filters.json
- Use ${page:60} so a filter clause is not required to extract page name
- :60 (10 chars more) still does not quite fill the horizontal field
- Change 'match' to 'ANY' (i.e. OR) so unrelated clauses may be added
=> filters.json: 28 'Hide Sponsored ... (SFX v24 beta)' improvements

filters.json
Covers many eu languages, plus Russian, Vietnamese, Chinese, Japanese.
Didn't try to tackle Indian / Arabic / Hebrew right now...
=> filters.json: 28 'Sponsored v24': add matching strings for common European & Asian languages

hideable.json
Was matching on `a[href^='/groups/']`, now encountering some badges which are instead `a[href^='https://www.facebook.com/groups/']` -- better use `a[href*='/groups/']`.
=> hideable.json: fix matching in 'Post Header: xyz Badge' hiders 279/280/304/305

filters.json
- make 10 'PYMK' language-neutral & deal with recent format change
- make 28 'Sponsored v24' better at seeing 'about ads' URLs
- fix typo 'spoliers' in 2 more-or-less obsolete spoiler filters
=> Several minor filter updates

hideable.json
Not an issue for 246 'Post: Recommend a place', which doesn't use
'parent' referencing and is therefore rendered as a static CSS rule.
=> hideable.json: 302 'Discover Members' don't fail if hide.js races post_processor.js

filters.json
1. minor: catch a rare alternate form of ad in the main Sponsored filter
2. major: push out an update to the 6 obsolete Sponsored filters, meant to catch the attention of people who are still using the old ones.  They would see items like below, in their News Feed -- of course, interleaved normally with non-ads.  The link is to a public post on my Timeline, so visible to all users; it contains multiple instructions to join the support Group, but the reader doesn't need to do that to execute the SFx repair instructions.
This will hit only people who still have the old filters subscribed; and furthermore, only if those filters actually catch a post.  So in that regard it is not completely effective, but should at least help.
People who have them subscribed but they aren't catching any posts …
=> Sponsored filter changes

hideable.json
Although I can find no history of this, my saved settings have #199 with
"parent: .mtm", which is wrong; and users are reporting trouble with
this hider, so I think they somehow have the same thing.  (#149 is
the only hider which has ever actually had '.mtm'; no idea how it got
transposed onto #199.)
To override this, put a zero value, which is read by the code as 'no
parent', but will cause retrieve_item_subscriptions() to erase '.mtm'.
(I will fix retrieve_item_subscriptions() later...)
=> hideable.json: update 199 'News Feed: Stories' to not have a parent

filters.json
These catch a fraction of ads, will imperfectly help while the main
has-visible-text() filter is currently outraced:
- ._5pcr ._5-sh
- ._5pcr a._34k6[ajaxify*='/verified_voice_context/']"
- ._5pcr ._3nlk,._5pbw a,._5pbw~a:contains(^Sponsored)
The last one applies ':contains()' to all 3 selectors, an intentional
use of SFx's weak CSS parsing -- properly should need to be:
._5pcr ._3nlk:contains(^Sponsored),
._5pbw a:contains(^Sponsored),
._5pbw~a:contains(^Sponsored)
=> filters.json: add selectors to 28 'Sponsored v24'

hideable.json
This appears right next to / overlapping 22 'Chat: Facebook Messages pop-under conversations'; can't be helped with current tools.
When nub is hidden, kbd help still appears when hit '?', as a floating box not connected to the bottom rail.
=> hideable.json: add 312 'Nub: Keyboard Shortcut Help'

filters.json
filters.json: 28 'Sponsored' show $author, not $page: some ads are now 'from' apps
filters.json: recognize 'Chartered' as an ad in 28 'Sponsored' (needs i18n)
'Chartered' probably represents a new wave of them adding multiple
synonyms for 'Sponsored', presumably in every language.  So things
gonna get ugly for a while again...
=> tweaks to Sponsored filter

filters.json
The '._5pbw a ... Spons' clause was mistakenly catching user / Group /
Page names starting with 'Spons', 'Chart', or any of the other-language
ad keywords.
Removing this clause will make the filter slightly weaker; but only a
small sub-class of ads were responsive to this clause in the 1st place.
Re: fb.com/2485097014892498
I may reinstate later with more specific class path, after further
research / observation.
=> filters.json: 28 'Sponsored' remove overly aggressive clause

hideable.json
We (group admins) agreed we wouldn't prevent people from hiding this sort of stuff.  Anyone seeking info on this has a wealth of options and if they explicitly want to hide FB's, that's their business.
=> hideable.json: add 316 'Left Col: COVID-19 Information Center'

hideable.json
hideable.json: add 318 'Marketplace Post: Information about Covid-19 for buyers and sellers' ([fb.com/246970563375495](https://fb.com/246970563375495))
hideable.json: add 319-341, items on a Page owner's display ([fb.com/246423846763500](https://fb.com/246423846763500)):
319 'Page Owner: Composer Bar'
320 'Page Owner: Invite friends to like your Page'
321 'Page Owner: Our Story'
322 'Page Owner: various reach / boost options'
323 'Page Owner: Get Started With Automated Ads'
324 'Page Owner: ads-n-reach box'
325 'Page Owner: Set Up FAQs'
326 'Page Owner: Set Up FAQ answers'
327-* 'Page Owner: Page Timeline Create Page'
328-* 'Page Owner: Page Fundraiser Campaigns'
329-* 'Page Owner: Page People'
330-* 'Page Owner: Page Review Needy Place Card'
331-* 'Page Owner: Page Locations'
332-* 'Page …
=> Marketplace & Page Owner hideables

hideable.json
This selector might not be specific.  I've seen the targeted area used
for 2 different things; the other was today, about a video about racial
injustice.  This selector distinguishes between those two, but might
pick up any other top-of-news-feed splash they add which lacks an href
(the video had an href).  The 3 newest-style classes I'm selecting on
are the ones that seem most specific to *this* presentation, thus least
likely to be repeated on some other use of the area.
I'm not using the hider myself, instead have a dashed border CSS to
keep an eye on it.  If I see something else highlighted I'll be able to
either fix this, or abolish it if I can't make a sufficiently specific
hider.
=> hideable.json: add 350 'Above Group Feed: Introducing Messenger Rooms for Groups'

hideable.json
hideable.json: add 352 "Chat Pop-Under: 'Start Voice Call' button"
hideable.json: add 353 "Chat Pop-Under: 'Start Video Call' button"
hideable.json: add 354 "Messages: 'Start Voice Call' button"
hideable.json: add 355 "Messages: 'Start Video Call' button"
=> Video & Voice call buttons for pop-under & full-page chat

filters.json
- use $0, not $1 ($0 = whole found string, $1 = parenthesized substring iff one exists)
- search for 'covid-19' and variants before 'covid' to improve note text
- add 'SARS CoV-2' to matchwords
=> filters.json: update 20200713 'covid'

filters.json
- 'the virus|this virus' are way too non-specific
- 'match_partial_words' seems unhelpful except 'face maskS', so look for
that explicitly.  'surface masks' might be used in house painting & IC
manufacturing...
=> filters.json: refine 20200713 'covid'

hideable.json
(screenshot is from a post asking about such things, which itself includes a screenshot which includes part of the 'voting center' text -- seen above the live-link hideable in the image)
=> hideable.json: add 2020091901 'Post: Voting Information Center'

hideable.json
Previous selector didn't always work, I think due to FB dynamic
rearrangement of the HTML structure (just a guess).
=> hideable.json: fix 2020091901 'Post: Voting Information Center'

tweaks.json
On committing this, and when people's tweak update cycles complete, people who had lower left ephemeral notifications hidden on 'old FB' will have them hidden on 'new'.  We may hear some support questions about that...
The top of the notification structure is now:
<ul class="lfi1tu6t p7hjln8o poy2od1o re5koujm kavbgo14">
.lfi1tu6t { bottom:16px; }
.p7hjln8o { list-style:none; }
.poy2od1o { position:fixed; }
.re5koujm { left:16px; }
.kavbgo14 { z-index:2; }
<li class="pedkr2u6 g3zh7qmp pc15xi3s r5qslco7 ilcmz9jb q9uorilb pmk7jnqg j9ispegn" style="bottom: 0px;">
.pedkr2u6 { opacity:1; }
.g3zh7qmp { transform:scale(1); }
.pc15xi3s { transition-duration:var(--fds-duration-short-in); }
.r5qslco7 { transition-property:transform,opacity; }
.ilcmz9jb { …
=> tweaks.json: update 3 'Hide Notification Bubble' to support 'new FB'

filters.json
Multiple users are reporting bursts of ads.  One showed me HTML in which
the UI language's 'Sponsored' word appeared in an <a role='link'> rather
than role='button'.  While it is likely this isn't the only change
needed, it's a step forward.
This also consolidates two selectors back to one.  The expression relies
on a fault in the SFx filter engine's CSS parsing enhancements.  Proper
CSS parsing would apply :has-visible-text() only to the immediately
preceding selector.  In reality, the entire string of alternating CSS
rules is evaluated first; then filtered by the :has-visible-text() rule.
The consolidation reduces double-processing of the regular expression
and differential drift of fixes over time (like the next item).
'Sponsored' is removed from the list of words, as it is handled by …
=> filters.json: update 28 'sponsored' for latest 'new FB' changes

hideable.json
hideable.json: add 2020120701 'Header: 'f' button"'
hideable.json: add 2020120702 'Header: 'Search Facebook' box"'
hideable.json: add 2020120703 'Header: 'Home' button"'
hideable.json: add 2020120704 'Header: 'Gaming' button"'
hideable.json: add 2020120705 'Header: 'More (Bookmarks)' button"'
hideable.json: add 2020120706 'Header: 'My profile' button"'
hideable.json: no longer redundantly tagging '(New Layout)' (but didn't clean old ones)
=> more header / navigation bar buttons

filters.json
filters.json: 1 'Sponsored', change 'Chart' to 'Chartered$' to more precisely match the 'English (Pirate)' word for Sponsored -- was matching a link to a business 'Charting Creations'
=> fix a false match in Sponsored filter

filters.json
lrazzd5p is 'bold'
q66pz984 is 'accent color'
m9osqain is 'secondary text color'
1st added expression should work everywhere; 2nd is English-UI-specific
=> filters.json: update 10 'People You May Know' for new layout

hideable.json
Can't use 'html[context_type=...]' because the hider CSS for any
hideable is html:not(.sfx_hide_show_all) ${hider}, and nested
'html html' selector won't work.  The constructor of the hider CSS
would have to know how to merge 'html' selectors.
=> hideable.json: 2021010424 'Left Rail: Messenger': last fix was bad, do better

filters.json
- move :contains() clause to a separate rule to avoid incorrect scoping
- this fixes the other new-layout clause + the old-layout clause
- sometimes it's 'People you may know' rather than 'People You May Know'
=> filters.json: update 10 'People You May Know'

hideable.json
hideable.json: add 2021012401 'Right Rail: Sponsored item (2)' for items without <a> links
hideable.json: add 2021012402 'Header: 'Friends' button'
Sponsored (2) per FB chat off of fb.com/469026214503261
Friends button per existing pattern & users' reports of what the friends button points to.  My account refuses to have one.
=> two new hiders

hideable.json
2021010501 'Right Rail: Sponsored item' is updated to the prior contents of
2021012401 'Right Rail: Sponsored item (2)', except no '[role=button]'.
Turns out the 2nd form is how FB present ads to some people, then when the
ad is moused over, it morphs into the first form.  This means they can't
hide the 2nd form because while trying to hide it, it morphs into the 1st
form!  So, need a hider which encompasses both forms.
Unfortunately this makes the entire hider a 'parent' type hider, which is
slower, so now you see the ads briefly on every page load.
=> hideable.json: fix Sponsored item hiders for real

hideable.json
Change parent from 'a[aria-label]' to simply 'a', because some apparently don't get aria-labeled.
The sample I saw *did* have 'aria-labelledby', but I'm not going to swing at that tarbaby.
=> hideable.json: fix 2021010501 'Right Rail: Sponsored item' once more

hideable.json
The selector for this is particularly ugly, derived from a single
example (which I have a copy of) from Ieda.  As with all these
new-layout selectors, it's my guess of what unique page-construction
details lead down to this item; the only definitive bit is
a[href*='groups/discover'], but that could hit all sorts of other
things, so then I construct a path to the box out of whatever
weird things it has -- in this case including 'flex-grow:0' and
'.t7l9tvuc:last-of-type{margin-right:0}'.  Which makes it fragile to
future FB changes, but unlikely to hide things I don't intend...
=> hideable.json: add 'Groups Feed: ad to join groups'

tweaks.json
It was hiding them, except there was a transition effect which caused
them to expose for a fraction of a second.
=> tweaks.json: fix 'blips' with 3 'Hide Notification Bubble'

hideable.json
- update 2020120706 'Header: 'My profile' button' to position hider correctly
- add 2021042901 'Header: 'Notifications' menu'
- add 2021042902 'Header: 'Create / Menu' menu'
- add 2021042903 'Header: 'Messenger' menu'
- add 2021042904 'Header: 'Pages' button'
- add 2021042905 'Header: 'Account' button [DISABLED]' (*)
(*) Support team agreed this was too dangerous to offer; this records
its method, in case there's a future reason to offer it.
Some of these hiders use aria-label matching, which means they only
work when the FB user interface language is English.  For Create/Menu,
Messenger, and Account (DISABLED), I was unable to create a working
hider which didn't rely on aria-label.  For Pages and Notifications, I
supply aria-label as a 'backup' so the hider might continue to work
under …
=> hideable.json: add and update some top bar buttons

hideable.json
hideable.json: update 2021051502 'Right Rail: Friend Requests (list)' for variant DOM version
hideable.json: update 2021051503 'Right Rail: Friend Requests (entire block)' for variant DOM version
User showed me their version of [data-pagelet=RightRail] in which the Friend Request friend links didn't have /requests in their URLs.
=> update 'Right Rail: Friend Requests' for variant DOM version

hideable.json
Some users lack #ssrb_stories_start; all have [data-pagelet=Stories].
Also updated title (of this and 'Rooms') to match others -- don't need
to mention 'New Layout', and we use FB's 'News Feed' orthography, not
'Newsfeed'.
=> hideable.json: update 2020082301 'News Feed: Stories' for variant layout

hideable.json
- add 2021052901 'Group Admin: 'Admin Assist' advertisement'
- add 2021052902 'Group Admin: 'Pending Posts' header'
- add 2021052903 'Group Admin: Pending Posts search-by-name box'
- add 2021052904 'Group Admin: Pending Posts bulk approve / decline'
These use "parent" to jigger the timing so that html[sfx_context] stuff
is ready (the first one needs it anyway).
=> hideable.json: hiders for group admin pending posts screen

hideable.json
Some of the URLs don't have '/media/' or even '/groups/'.  Add
recognition of '/photo/' and '/video/', which should catch *most*
instances of the media box.  Since these URLs don't have '/groups/',
use '[data-pagelet=DiscussionRootSuccess]' to enforce that we're
looking at a Group, not some other sort of page.
('.bexiecsf' is seen on the persistent notifications page when looking
at a Group post, while '.lntdvkbv' is on a whole-Group page)
=> hideable.json: improve 2020121303 'Group Right Col: Recent Media'

hideable.json
hideable.json: add 2021082201 'News Feed: Add a WhatsApp Button' (fb.com/611633040242577)
hideable.json: non-'parent' hiders with alternate definitions cannot be unhidden due to how SFx composes the CSS (fb.com/4086152861496198)
hideable.json: 2021042905 "Header: 'Pages' button": remove alternate definition
hideable.json: 2021050101 "Header: 'News' button": remove alternate definition
=> 'WhatsApp Button' + fix two header button hiders

hideable.json
hideable.json: add 9 hiders for ads in the right column of games:
- 2021092201 'Games Right Col: Tournaments'
- 2021092202 'Games Right Col: Featured Game (1)'
- 2021092203 'Games Right Col: Featured Game (2)'
- 2021092204 'Games Right Col: Top Games'
- 2021092205 'Games Right Col: Instant Games'
- 2021092206 'Games Right Col: Games Your Friends Play'
- 2021092207 'Games Right Col: Game Category' (*)
- 2021092208 'Games Right Col: Your Games'
- 2021092209 'Games Right Col: Gaming Video'
(*) I assume this will cycle through different categories other than
'Puzzle Games', though that's all I've seen.  There's nothing to
distinguish the categories other than the title, which isn't really
accessible to a hider.
hideable.json: retire old versions of 2 of these (244 & 247)
hideable.json: use …
=> Games hiders, per fb.com/631732744899273

filters.json
The filter has been called 'Sponsored and Suggested' forever, but the word 'Suggested' came from early FB weasel words about ads, **not** their later propensity for adding all sorts of 'Suggested Posts', 'Suggested Groups', etc.  This has been an ongoing source of confusion and displeasure for users.
This now adds a 'Suggested' filter which covers all the sorts of suggested-post crud I am aware of at the moment.  Of course it will need to be updated frequently since they are ever creative in this regard.
(Testing it today on fb.com/groups, I saw at least one instance of a post from a group I am not associated with, posted by a person I am not associated with, with **no** 'Here is some crap we thought you'd like' action-string.  I don't see how we can filter those except by keeping a list …
=> Split 'Suggested' off from 'Sponsored' filter

hideable.json
hideable.json: add 2021100501 'Right Rail: Recently Saved'
hideable.json: add 2021100502 'Right Rail: Watch'
hideable.json: add 2021100503 'Give Award (Post Comment)'
hideable.json: add 2021100514 'News Feed: Rooms [alt]' using #ssrb_composer_start, as
[data-pagelet^=VideoChatHomeUnit] is absent for some users
hideable.json: change 2020082301 'News Feed: Stories' to use [href] as
[data-pagelet=Stories]"} is absent for some users
hideable.json: add 'alt' Right Rail hiders using #ssrh_rhc_start, as
[data-pagelet=RightRail] is absent for some users:
hideable.json: add 2021100504 'Right Rail (entire block) [alt]'
hideable.json: add 2021100505 'Right Rail: Sponsored [alt]'
hideable.json: add 2021100506 'Right Rail: See All Contacts [alt]'
hideable.json: add 2021100507 'Right Rail: Birthdays …
=> some new & updated Right Rail & News Feed hiders

hideable.json
Beginning of an effort to purge Old Layout hiders.  Fewer hiders =
faster Hide/Show startup time, less memory churning.  These hiders
appeared only on the Old Layout main News Feed page, which there is
no way to reach any more.
No elements remain on the News Feed page with IDs of the forms
'navItem_*' or '*Nav'.  The related FB internal server modules
are seen to be fully obsolete.
=> hideable.json: remove 80 'Left Rail: blahblah' Old Layout hiders

hideable.json
Replacing 2021010423's payload didn't work, neither as comma-separated
old,new nor as just the new selector.  Don't understand why, but, this
means it'll continue to work for people with either code sent down by
FB, although they'll have to re-hide it when it transitions.
=> hideable.json: add 2021100601 'Left Rail: Memories (2)'

hideable.json
Some users get a Right Rail with [data-pagelet=RightRail]; others lack
that.  I don't know what else is different in the structures, but
empirically the two sets of hiders do work.  However, if a single user's
FB switches back and forth, sections can be hidden by one while the
other still matches and displays a hider *on top of* the unhider for the
other one; making it impossible to unhide.
With these mutually exclusive hiders, the user may need to re-hide
things they previously hid; may need to hide things twice, as FB flip
them back and forth between code sets.  But at least everything will
work rationally.
Both sets could be combined using CSS comma alternation (on both the
selector & parent selector).  But I did that before and had problems that
I can't remember the details of. …
=> hideable.json: make Right Rail alt and not-alt entries mutually exclusive

hideable.json
hideable.json: add 2021111601 'Left Rail: Oculus (2)', alternate to 2021010428
hideable.json: add 2021111701 'Post: Ask Your Community for Support' (fb.com/655108652561682)
hideable.json: add 2021111702 'Group Feed: See the latest coronavirus info'
hideable.json: adjust a couple old entries for consistency
hideable.json: for Left Rail, use '#ssrb_left_rail_start' vs '[role=LeftRail]' (fb.com/669015097837704)
Most users get a Left Rail with '[data-pagelet=LeftRail]'; others
lack that.  '#ssrb_left_rail_start' seems to be universal.
no pics for others
=> Make Left Rail items more universal, plus 3 new hiders

hideable.json
hideable.json: use more universal selectors for the roots of Left & Right Rails
hideable.json: retire the set of 'Right Rail [alt]' hiders
hideable.json: rename 2020082901 'Left Rail (entire block)' + better self-doc
hideable.json: reduce 2021111601 'Left Rail: Oculus (2)' chances to hide groups
Users continue to experience hiders which work some of the time, as FB
randomly shuffle their layouts and stuff.
This is researched from all the saved FB HTML I have since 'new layout'
started; including a number of pages sent in by users with different
hardware, browsers, etc., in pursuit of various old unrelated problems.
I've now seen examples of pages which have '#ssrb_left_rail_start' and
'#ssrb_rhc_start' but lack '[data-pagelet=LeftRail]' and
'[data-pagelet=RightRail]'.  I've seen examples …
=> More work on Left / Right Rail

news.json
I'm not immediately merging this, on the change that Matt might have done this on purpose for a sort of 'Streisand' effect.  Will try to reach him.
=> news.json: fix 'Giviting Tuesday' spelling :)

hideable.json
hideable.json: 2021010404 'Left Rail: Watch' avoid /watch left col items
hideable.json: add 2021120801 'Left Rail: Watch (2)' -- comma won't work
hideable.json: 2020082901 'Left Rail (entire block)' avoid non-News Feed
Left Rail on Top Stories, Most Recent, Favorites is the same thing (grab
bag links like 'Recent Ad Activity') -- while Left Rail on task-specific
pages like Marketplace, Groups Feed, Watch, are task-specific bars which
should not be hidden.
Tested on the above 6; this will improve the situation whether or not it
fixes all possible issues...
=> Fix some Left Rail items which wrongly affect non-News Feed pages

hideable.json
hideable.json: add 2022020701 'Group Right Col: Create subgroup'
Note new higher-level coordination point for group right col: .rek2kq2y.l9j0dhe7.aghb5jc5
-- could modify other group right col items to use it; might need to, eventually.
.rek2kq2y { overflow-anchor:none; }
.l9j0dhe7 { position:relative; }
.aghb5jc5:empty { display:none; }
.lpgh02oy { position:sticky; }
.oygrvhab { margin-bottom:0px; }
.ii04i59q { white-space:pre-wrap; }
.gs1a9yip { align-items:stretch; }
.i1fnvgqd { justify-content:space-between; }
.owycx6da { flex-wrap:nowrap; }
hideable.json: update 2020121301 'Group Right Col: About' for current HTML
=> one new, one updated Group Right Col hiders

hideable.json
hideable.json: add 2022021801 'News Feed: Keep your Page up to date'
hideable.json: add 2022022501 'News Feed: Facebook ad discount'
hideable.json: update the top-of-News-Feed anchor point selectors in:
hideable.json: - 2021041101 'News Feed: Remember Password prompt'
hideable.json: - 2021041102 'News Feed: Take A Survey prompt'
hideable.json: - 2021082201 'News Feed: Add a WhatsApp Button'
hideable.json: - 2021101501 'News Feed: Finish Donation'
I've seen pages which loaded without #ssrb_composer_start.  I think this
anchor will be more stable.  But can't really test it, so will wait for
user reports...
2020082302 'News Feed: Rooms' should also be treated this way, but is
too complex for me to do blindly
No pic for the 'Keep your Page up to date'.
=> 2 new News Feed annoyances, plus updates:

hideable.json
hideable.json: fix old-FF compatibility of 2021041101, 2021041102, 2021082201, 2021101501, 2022021801, 2022022501
In commit a129bc24 I wrote: 'I think this anchor will be more stable.  But can't really test it, so will wait for user reports...'
fb.com/741404923932054 is a user report that Hide/Show doesn't work on FF 79.  I verified in FF 78esr: selectors of the form ':not(.this,.that)' do not work.  So, fix those selectors to be back-compatible: ':not(.this):not(.that)'.
Affects hiders: 'News Feed:{ Remember Password prompt, Take A Survey prompt, Add a WhatsApp Button, Finish Donation, Keep your Page up to date, Facebook ad discount}'
=> fix a set of hiders which broke compatibility with older Firefox

filters.json
Initially supports:
- Wordle
- Dordle (*)
- Quordle
- Octordle (*)
- Worldle (*)
- Globle (*)
- Nerdle (*)
- Scholardle
- any related game which uses the same Unicode chars to represent their 'board'
More are likely to be added.
There is some chance the Unicode 'alt' catchers will pick up some kinds of
non-xyzdle posts.  I expect to hear about it...
(*) Only tested on my own test post of that game; Wordle, Quordle &
Scholardle tested on 'real' live News Feed post by my friends...
=> filters.json: add 20220317 'Wordle'

hideable.json
Multiple reports that it is blanking out the entire News Feed in various
situations.  Can't fix it right away; at least disable it until I figure
out what's wrong.  Unfortunately SFx 28 users still have to go into
Hide/Show, Done Hiding, before the update will be received.
=> hideable.json: temporarily disable 2020082302 'News Feed: Rooms'

hideable.json
hideable.json: fix 2020082302 'News Feed: Rooms' once again
hideable.json: safer parent for 2021041101 'News Feed: Remember Password prompt'
hideable.json: safer parent for 2021041102 'News Feed: Take A Survey prompt'
hideable.json: safer parent for 2021082201 'News Feed: Add a WhatsApp Button'
hideable.json: safer parent for 2021101501 'News Feed: Finish Donation'
hideable.json: safer parent for 2022021801 'News Feed: Keep your Page up to date'
hideable.json: safer parent for 2022022501 'News Feed: Facebook ad discount'
hideable.json: New Layout version of 2020082502 'Post: View Insights'
hideable.json: retire 2020082503 'Post: People Reached': hider always appears 'under'
=> Fix News Feed hiders which could potentially hide whole NF

hideable.json
hideable.json: add 2022042201 'Group: community fundraisers'
hideable.json: add 2022042202 'Chat pop-unders (*ALL* CHAT POP-UNDERS, EVEN IF YOU MADE IT ON PURPOSE!) [DISABLED]'
Chat pop-unders is disabled because (from past experience) people turn
it on, then are completely flummoxed where their chat pop-unders went.
Enable it when 29.0 is shipping, with fully operational tooltips...
=> 2 new hideables, one pre-disabled until tooltips work

hideable.json
hideable.json: rename 2021042904 to 'Your profile' due to FB change
hideable.json: fix 2021042904 'Your profile' due to FB tooltip change
hideable.json: thus rename 2020120706 to 'Self'
hideable.json: fix 2020120706 'Self button', broken by hide.js ce2915e5
Reminder to myself: I occasionally retry to hide the top-bar buttons
with space removal (rather than just hiding their icons).  This doesn't
work because:
- on the right side (My profile, Menu, Create, Messenger, Notifications,
Account) -- the buttons themselves are at the top of their respective
HTML structures; hiding the parent hides all buttons at once
- on the left side ('f', Search, Home, Watch, Marketplace, Groups, News,
Gaming, Friends, Pages, Events, Bookmarks) -- it is possible to hide
the buttons and *part* of their space. …
=> top bar button hider fixes

filters.json
Forgot to edit 'ALL' to 'ANY', so it insisted on *both* one of the
existing clauses *and* 'Reels'; which presumably = no posts ever...
=> filters.json: fix bonehead error in 2021082601 'Suggested'

tweaks.json
Beginning of a flood.  They've completely replaced their previous suite of gibberish selectors with new ones; which appear, again, to be consistent across all users.  If they replace them every 2-3 years like this I guess it will be sort of tolerable.
Updates needed in other tweaks; hideables; a few filters; and quite a few places in SFx code itself.
wheeee.
=> tweaks.json: update 3 'Notification Bubble' for new FB gibberselectors

filters.json, hideable.json, tweaks.json
This more or less brings everything up to date for the new set of classes.
All of the hiders, filters and tweaks have been kept backwards compatible with the 2020 classes, as I can't yet tell whether the rollout is universal or rolling.
I deleted some pre-2020 ('old layout') support.  The old layout ._abcd selectors **are** still used internally, in various ways, but I don't think any of the uses here are still relevant (for 2+ years).
Not everything has been tested, but a lot has, and the hit rate of the ones I was able to test (because FB sent me the relevant thing-to-hide-or-filter) was high enough to feel that all will work.  If not, it's mostly failure-by-omission: it won't filter the post, or won't hide the annoyance; there shouldn't be any whoops-hides-too-much.  I hope :)
Filters …
=> update socialfixerdata for 2022 gibberish classes

filters.json
Publishing versions of these filters with the CSS gibberish names pre-resolved, as the S2F_ ones don't do anything until SFx 29...
=> filters.json: prechew gibs in 10 'PYMK', 28 'Sponsored', 2021082601 'Suggested'

filters.json
filters.json: 2021082601 'Suggested' add group name to the click-to-see
filters.json: 2021082601 'Suggested' fix totally wrong negative lookahead
The negative lookahead is meant to capture group names in 'More like' and 'Suggested groups' fakeposts, which are structured with a 'xyz number of posts a day/week/month' teaser followed by actual group names. Which is then, these days, followed by Facebook's selfarrhea, so use a negative lookahead to chop that off.
The wrong negative lookahead was totally breaking the filter...
=> Fix and improve 'Suggested' filter

filters.json
These use :contains().  Must use the correctly wrong hybrid syntax 'this,that:contains(thing)', not 'this:contains(thing), that:contains(thing)' -- as doc'd in my own 'DOC' statements.  argh!
=> filters.json: *correctly* prechew gibs in 10, 28, 2021082601

filters.json
filters.json: add 2023011201 'Hide Reels'
The clauses I added in the previous commit hide individual user's 'Reels' posts, which are actually legitimate user creations or 'shares'.  Moving those out of 'Suggested' and into their own separate 'Reels' filter.
'Suggested' continues to hide FB Reels fakeposts ('here are 5 suggested Reels').
=> filters.json: revert Reels part of 2021082601 'Suggested'

filters.json
filters.json: 2021082601 'Suggested' check ${action} as well as ${all_content}
This is a workaround for occasionally blank ${all_content} (see SFx commit 540c80a).
Fix suggested by data from fb.com/963247941747750
=> Fix occasional lapse in 'Suggested' filter

filters.json
- Hexadecordle also consult image caption as some samples crow as an image
- add one more UNICODE 'color square' character to CSS-only matcher
- new clause captures adequate hide-string for the final CSS-only matcher
- works by using :contains() with a successful regex -- in a NOT clause, so ${1} is collected, but we don't match; don't stop processing clauses
- the new clause tries to trim away some trash, but isn't 100% effective; resulting hide strings will be trashy but understandable
- trimming is English-specific: intl FB UI users will get more trash :(
- use '${any}' to capture '${1}' or '${2}' depending on English vs. intl match
- trim final output strings to avoid huge trashtext blocks
=> filters.json: improvements to 2022031701 'Wordle'

filters.json
Lots of users complain about  the Control Panel being activated by subscription filters.
This and the two 'create tab' filters ('Create Author Tabs', 'Create Game/App Tabs') are the only subscription filters which activate the CP.  The other two inherently require it for their functionality; this one is just an arbitrary choice, so I'm flipping the arbitrary choice.
=> filters.json: 11 'Friend Activity Stories' default to Hide post, not a tab

hideable.json
This was tricky because the blob-to-hide moves between top and right columns depending on zoom level.  This is not done with pure CSS; rather, FB rewrite *part* of the DOM on width changes.  I had to find a node which covered the entire blob but was not rewritten during a width change -- otherwise the blob would reappear on zoom in/out past the boundary size (but then disappear again on reload).
In the 2-column 'zoomed out' presentation, this also has the benefit of removing the space used, allowing the center column to expand.
=> hideable.json: add 2023071201 'Groups Feed: Chats you should join'

filters.json
filters.json: add modifier:"i" and matcher:"re" where needed
filters.json: add modifier:"I" where needed
filters.json: reword obsolete 'operator:"not_some_operator"'
This means data on matt-kruse.github.io/socialfixerdata/filters.json will now be compatible with SFx 29.0 and later.  However, only the change to 2022031701 'Wordle' would likely bother older releases, and I'm not sure if it would be particularly harmful.
This change opens the way for SFx >31.0 to stop trying so hard to internally canonicalize filters, which I believe is what's been causing filter corruption.
=> Modernize filter data structures

hideable.json
hideable.json: add 2023100301 'Profile: People You May Know (2023)'
per fb.com/1111120566960486 & conversation / field testing with user (testing still in progress, but it's gonna work and I'll add a screenshot then)
hideable.json: add 2023100501 'Profile: get Meta Verified'
per fb.com/1113301683409041, and then FB conveniently added it to my account...
=> 2 profile hiders: new PYMK + 'get Meta Verified'

filters.json
Suggested group posts now showing up with ${action} & ${all_content} looking like:
action:"Handle the HeatSuggested for you"
all_content:"Handle the Heat · Suggested for you · · Shared with Public ..."
with the group name in front of the 'suggested' weasel words.
per fb.com/1129472241791985
=> filters.json: adapt 2021082601 'Suggested' for recently modified header appearance

filters.json
Not fixing the others since the issue has no effect ('re' is the default).  Don't want subscribed copies to show new update time.
=> filters.json: fix 'matcher' clauses in 2021082601 'Suggested'

hideable.json
hideable.json: fix CSS syntax of 2024082001 'Pop-Up Refresh button'
=> hideable.json: add 2024092301 'Left Rail: Birthdays'; fix CSS syntax mistake

tweaks.json
They replaced .xe8uvvx { list-style: none; } with .x3ct3a4 { list-style-type: none; }
-- so, support both of those (the latter without gib support, until some maybe-future release of SFx).
Also clearing away ancient 2020 & 2022 decoded gib support.
=> tweaks.json: fix 3 'Hide Notification Bubble'
