- tweaks.json
Reverts matt-kruse/socialfixerdata#5
> Revert ""Remove Status Background Colors" improvements:"

- tweaks.json
Quotes (") needed to be quoted (\\")
> "Remove Status Background Colors" improvements, fixed JSON

- hideable.json
- hideable.json: tag duplicate names for support / debug purposes
- hideable.json: add 'Left Col: Weather'
- hideable.json: add 'Left Col: Town Hall'
- hideable.json: add 'Left Col: Order Food'
- hideable.json: add 'Left Col: Create a Frame'
- hideable.json: add 'Right Col: People You May Know (2)'
- hideable.json: add 'Right Col: Suggested Pages (3)'
- hideable.json: add 'Right Col: Create a Group'
- hideable.json: add 'Right Col: Recent Group Photos'
- known issue: user's settings JSON doesn't pick up name changes unless
they go into Hide/Show and toggle each individual hideable which was
renamed; SFx JS should handle this
> add 4 more Left Col & 4 more Right Col hideables, and differential duplicate names

- hideable.json
See https://facebook.com/1385378618197682
> hideable.json: fix 'Right Col: Suggested Groups' which sometimes appears outside of #pagelet_ego_pane

- tweaks.json
(sometimes it's sibling rather than child of the post)
> - tweaks.json: handle new variant of 'Related'

- tweaks.json
- including after clicking 'See Original' on a translated post
- as seen on [facebook.com/1319653494786064](http://facebook.com/1319653494786064)
> tweaks.json: "Remove Status Background Colors" handle more types of localized posts

- hideable.json
High demand for this, at least half a dozen threads today...
> - hideable.json: "Right Col: Sponsored Pagelet (2)"

- hideable.json
This is completely untested, working from a screenshot of 'inspect element' sent by a user.
I expect it'll work (and do no harm if it doesn't).
> - hideable.json: "Right Col: Local Products in Marketplace"

- hideable.json
- hideable.json: "Right Col: Watchlist: Latest Episodes"
- hideable.json: "Timeline Left Col: Intro (rotating question)"
- hideable.json: "Timeline Left Col: Add Featured Photos"
- hideable.json: "Timeline Left Col: Add Instagram, Websites, Other Links"
- hideable.json: "Timeline Left Col: Timeline Info Review"
> new hideables 'Watchlist' + several timeline annoyances

- hideable.json
- hideable.json: "Left Col: Explore Feed"
- hideable.json: "Left Col: Discover People"
> two more left col 'Explore' items

- hideable.json
- see facebook.com/1557148781036533 (discussion), facebook.com/748055561932820 (test case)
> - hideable.json: Page Right Col: Page Type, Community, About

- hideable.json
Re: [facebook.com/1515571471845062](http://facebook.com/1515571471845062)
> - hideable.json: Timeline Left Col: Did You Know

- hideable.json
- hideable.json: add "Timeline Left Col: Photos"
- hideable.json: add "Timeline Left Col: Friends"
- hideable.json: add "Timeline Left Col: Featured Albums"
- hideable.json: update "Timeline Left Col: Add Instagram, Websites, Other Links" to take out more space
> more butchery of Timeline left column

- hideable.json
- hideable.json: Right Col: Page Owner panel
- hideable.json: Right Col: Page Owner panel: Respond Automatically
- hideable.json: Right Col: Page Owner panel: Recent Posts
> Add some hideables for owners of Facebook 'Pages':

- hideable.json
So far seen:
- Respond Automatically If You're Closed This Holiday Season
- Learn How to Advertise on Facebook
More probably exist...
> - hideable.json: Rename 'Respond Automatically' to 'Page Owner tips'

- hideable.json
- hideable.json: update 'Page Right Col: Page Type' with better selector
- hideable.json: add 'Right Col: Page Owner: Chatbot'
- hideable.json: add 'Page Right Col: Have a Question About Your Page?'
- hideable.json: add 'Page Right Col: Page Tips'
- hideable.json: add 'Page Right Col: Page statistics'
- hideable.json: add 'Page Right Col: Team Members'
- hideable.json: add 'Page Right Col: Pages liked by this Page'
- hideable.json: add 'Page Footer: Insights This Week'
> more Page-related hideables

- hideable.json
Pic stolen from [facebook.com/2022030107825244](http://facebook.com/2022030107825244):
> - hideable.json: add "Right Col: Suggested For You"

- hideable.json
- hideable.json: add 'Group Right Col: Add Members'
- hideable.json: add 'Group Right Col: Member Count'
- hideable.json: add 'Group Right Col: Member Faces'
- hideable.json: add 'Group Right Col: Welcome New Members'
- hideable.json: add 'Group Right Col: Suggested Members'
- hideable.json: add 'Group Right Col: Group Type'
- hideable.json: add 'Group Right Col: Tags'
- hideable.json: add 'Group Right Col: Locations'
- hideable.json: add 'Group Right Col: Requests'
> Add hiders for various parts of group right column:

- hideable.json
(from [facebook.com/1564088786993330](http://facebook.com/1564088786993330))
> - hideable.json: add 'Right Col: Gaming Video / Live Now in Popular Games'

- hideable.json
> - hideable.json: add 'Right Col: What Your Friends Are Watching'

- hideable.json
> - hideable.json: add 'Right Col: Sponsored Pagelet (3)'

- hideable.json
> - hideable.json: add 'News Feed: Stories'

- hideable.json
(seen with titles 'Continue Watching on Facebook Watch' and 'Shows From Facebook Watch')
[facebook.com/1626086034126938](http://facebook.com/1626086034126938)
> - hideable.json: add 'Right Col: Continue Watching / Facebook Watch'

- hideable.json
For the record:
- hideable.json: add "Right Col: Timeline Create Page pagelet"
- hideable.json: add "Right Col: Fundraiser Campaigns pagelet"
- hideable.json: add "Right Col: People pagelet"
- hideable.json: add "Right Col: Review Needy Place Card pagelet"
- hideable.json: add "Right Col: Pages Suggested By Page Secondary pagelet"
- hideable.json: add "Right Col: SEO Interlinking Related Element pagelet"
- hideable.json: add "Right Col: Seo Related Topics pagelet"
- hideable.json: add "Right Col: Seo Related Pages pagelet"
- hideable.json: add "Right Col: Seo Related Groups pagelet"
- hideable.json: add "Right Col: Seo Related Events pagelet"
- hideable.json: add "Right Col: Locations pagelet"
- hideable.json: add "Right Col: Coupons pagelet"
- hideable.json: add "Right Col: Photos …
> Add 20(!) "Right Col: Some Sort Of Crap pagelet" entries

- hideable.json
> - hideable.json: add "Blue Bar: Account Switcher"

- hideable.json
- hideable.json: add "Page: post-component widgets 'See All'"
> - hideable.json: add "Page: post-component widgets"

- hideable.json
> - hideable.json: add "Page post comment: Instantly send this as a message to Page"

- hideable.json
> - hideable.json: embed some doc in "Post: Show more information about this article" title

- hideable.json
> - hideable.json: add 'Right Col: Rentals on Marketplace'

- hideable.json
- hideable.json: rename/repurpose 'Chat Dock' as 'Chat: Facebook Messages pop-under conversations'
- hideable.json: add separate 'Chat: Facebook Messages online list & settings'
> Split the chat hider

- hideable.json
to 'Chat: Facebook Messages online list / settings'; add selectors
which handle it at different zoom levels
> - hideable.json: rename 'Chat: Facebook Messages online list & settings'

- hideable.json
> - hideable.json: add 'Post: Turn on selling features'

- hideable.json
> - hideable.json: add 'Right Col: Previous Search on Marketplace'

- hideable.json
- hideable.json: add 'Chat: Create New Group'
- hideable.json: add 'Right Col: Recently Viewed on Marketplace'
> two new hideables

- hideable.json
Per [facebook.com/1680216872047187](https://facebook.com/1680216872047187):
> - hideable.json: add 'Right Col: Still Available on Marketplace'

- hideable.json
'Right Col: Featured on Facebook Watch' [facebook.com/1680811775321030](https://facebook.com/1680811775321030) ![hide-featured-facebook-watch](https://user-images.githubusercontent.com/3022180/40154922-e28c6ebc-5945-11e8-9ced-3869adb1b903.jpg)
'Far Right Col: Instant Games / Games Your Friends Play' [facebook.com/1680223588713182](https://facebook.com/1680223588713182)
> hideable: 'Featured on Facebook Watch' & 'Instant Games'

- hideable.json
> - hideable.json: add 'Post: Recommend a place'

- hideable.json
- hideable.json: add 'Right / Far Right Col: Your Games'
- hideable.json: add 'Right / ' to 'Instant Games', 'Games Your Friends Play' hider names
> more 'Games' hiders

- hideable.json
Re: [facebook.com/1689740804428127](https://facebook.com/1689740804428127)
> - hideable.json: add 'Group Right Col: Upcoming Group Events'

- hideable.json
> - hideable.json: add 'Group Post Feed: Search For Items'

- hideable.json
> - hideable.json: add 'Right Col: Unified Gaming Pagelet'

- hideable.json
> - hideable.json: add 'Post: Choose friends to tag'

- hideable.json
> hideable.json: add 255 'Left Col: Oculus'

- hideable.json
> hideable.json: add 256 'Left Col: Business Discovery'

- hideable.json
- hideable.json: reduce 236 to 'Chat: Facebook Messages online list / settings (popup when zoomed in)'
- hideable.json: add 258 'Chat: Facebook Messages online list / settings (entry box when zoomed out)'
> split 236 'Chat: Facebook Messages online list / settings'

- hideable.json
hideable.json: add 260 'Left Col: Group'
hideable.json: add 261 'Left Col: Page'
hideable.json: add 262 'Left Col: Fundraiser'
hideable.json: add 263 'Left Col: Event'
> 4 new (updated) hideables

- hideable.json
> hideable.json: add 264 'Group Post Feed: Post Your Items Publicly to Marketplace'

- hideable.json
> hideable.json: add 265 'Right Col: Translate Facebook'

- tweaks.json
(Sorry, committed this on my 'master' branch before realizing I needed to move it)
> tweaks.json: update 'Remove Status Background Colors' to handle newer style seen by Adam Tofts

- hideable.json
hideable.json: add 266 'Explore Live Gaming Videos'
hideable.json: add 267 'Left Col: Trending News'
hideable.json: add 268 'Left Col: Creator Studio'
> 3 new hideables

- hideable.json
> hideable.json: prepend 'Post: ' to 266 'Explore Live Gaming Videos'

- hideable.json
> hideable.json: add 269 'Right Col: Top Picks on Marketplace'

- hideable.json
> hideable.json: add 271 'Group: Items for Sale'

- hideable.json
See [https://facebook.com/1860815287320677](https://facebook.com/1860815287320677)
> hideable.json: add 273 'Post: Looking for Recommendations'

- filters.json
(knowingly not updating the date in the title for this minor change)
> filters.json: 'is_sponsored=0' should not trigger the Sponsored filter

- hideable.json
> - hideable.json: add 276 'Left Col: 2018 Election'

- hideable.json
(seems to come in 'may like' and 'might like' variants which I believe are internally the same...)
> - hideable.json: add 277 'Right Col: Games you might like'

- hideable.json
hideable.json: add 278 'Right Col: Today's Games'
hideable.json: add 279 'Post Header: Conversation Starter Badge'
hideable.json: add 280 'Post Header: New Member Badge'
> add three hideables

- hideable.json
> hideable.json: add 281 'News Feed: Mentorship ad for admins'

- hideable.json
hideable.json: add 282 'Friend Finder: People You May Know'
hideable.json: add 283 'Blue Bar: Friend Requests: People You May Know'
> add PYMK hiders

- hideable.json
hideable.json: add 284 'Memories: Year In Review section'
hideable.json: add 285 'Right Col: Connect with Facebook'
> 'Year In Review' and 'Connect with Facebook'

- filters.json
filters.json: separate the selectors of 24 'Hide Sponsored/Suggested Posts (OLD)' so I can get debug info from users who start getting all posts hidden
> 'Sponsored (OLD)' debuggability

- hideable.json
hideable.json: add 286 'Chat Sidebar: profile pic'
hideable.json: add 287 'Chat Pop-Under: titlebar profile pic'
hideable.json: add 288 'Chat Pop-Under: top of conversation profile pic'
hideable.json: add 289 'Chat Pop-Under: speaker profile pic'
hideable.json: add 290 'Messages: speaker profile pic'
> profile pics in chat

- hideable.json
(ignore development-in-progress-and-bad Hide/Show accessibility / visibility work...)
> hideable.json: add 291 'Left Col: Send or Request Money'

- hideable.json
hideable.json: add 292 'Post: Click To Play button'
hideable.json: add 293 'Post: Play button'
> Hideables for posts with embedded games

- hideable.json
hideable.json: add 295 'Post: Start Watch Party'
hideable.json: add 296 'Post: Become a Supporter'
> couple of interaction buttons inside posts

- hideable.json
> hideable.json: add 297 'News Feed: Save Password'

- hideable.json
> 'Left Col Shortcuts: events' & 'Left Col: Quiet Mode'

- filters.json
filters.json: 26 'Sponsored D' recognize 'Contact Us' button
filters.json: 26 'Sponsored D' recognize buttons more widely
> 'Sponsored D' improvements

- hideable.json
> hideable.json: add 300 'Right Col: Reminders: Events (2)'

- hideable.json
> hideable.json: add 301 'Post: More From (name of Page)'

- hideable.json
> hideable.json: add 303 'Right Col: Sponsored Pagelet (4)'

- filters.json
[fb.com/2165394093529460](https://fb.com/2165394093529460)
> add an 'action' matcher to 9 'Hide "Shared Memories"'

- hideable.json
Image shows user trying this out via 'Custom Hideables' and a separate hider looking only for the new selector:
> hideable.json: update 132 'Right Col: Suggested Pages (2)' with additional selector

- filters.json
also format to match other entries
> filters.json: 28 (Sponsored v24 beta) add clauses needed from 'current' filter

- filters.json
Change title to reflect actual purpose:
- Election/Politics 2019 => US Election/Politics 2019
Remove first names whose last names are sufficiently unique:
- amy klobuchar => klobuchar
- eric swalwell => swalwell
- jay inslee => inslee
- john hickenlooper => hickenlooper
- kirsten gillibrand => gillibrand
Split whose both names are sufficiently unique:
- tulsi gabbard => tulsi|gabbard
Add sufficiently unique last name:
- => o'rourke
Add last name to insufficiently unique first names:
- bernie => bernie sanders
- hillary => hillary clinton
Add 2nd spellings:
- bill weld
- julián castro
Add 2 further declared + 2 highly leaning Democratic candidates:
- wayne messam (as 'messam')
- mike gravel
- michael bennet
- stacey abrams
Add one politics / flame word:
- => maga
Change for consistency:
- …
> filters.json: polishing / update of 1 '[US] Election/Politics 2019'

- filters.json
> filters.json: 29 'Hide Avengers: Endgame Spoilers' match whole words,

- hideable.json
hideable.json: add 305 'Post Header: Visual Storyteller Badge'
hideable.json: fix slight format inconsistency (whitespace)
> hideable.json: add 304 'Post Header: Rising Star Badge'

- hideable.json
hideable.json: add 306 'Timeline Left Col: Intro'
hideable.json: add 307 'Timeline Left Col: Life Events'
> two more Timeline Left Col hideables

- hideable.json
> hideable.json: add 308 'Marketplace: Sponsored'

- hideable.json
hideable.json: add 309 'Left Col: Liked Pages'
hideable.json: add 310 'Post: Add this photo to your story?'
hideable.json: add 311 'Post: Ask Your Community for Support'
> 3 new hiders

- hideable.json
> hideable.json: 201 'Right Col: Reminders: Birthdays' update with currently working selector

- hideable.json
> hideable.json: add 314 'Right Col: Videos From Facebook Watch'

- hideable.json
[fb.com/220718666000685](https://fb.com/220718666000685)
> hideable.json: add 315 'Group Right Col: Categorize Posts / Create Topic'

- hideable.json
hideable.json: add 342 'News Feed: Video Chats' (no pic)
hideable.json: add 343 'Group Right Col: Invite Members'
hideable.json: add 344 'Group Right Col: Invite Friends'
hideable.json: add 345 'Group Right Col: Write a post to welcome new members'
> 4 new hiders

- hideable.json
hideable.json: add 346 'Chat Sidebar: Group Conversations'
hideable.json: add 347 'Chat Sidebar: More Contacts'
> hide sections of chat dock

- hideable.json
> hideable.json: add 348 'Left Col: Facebook Pay'

- filters.json
-- not sure if these catch anything more, but users are suffering, let's try...
> filters.json: 28 'Sponsored' add selectors from old filters which still catch

- hideable.json
> hideable.json: add 351 'Post Comments: Facebook comment quality survey'

- filters.json
Re: [303057001100184](https://fb.com/303057001100184)
> filters.json: add Hebrew ad-word to 28 'Sponsored'

- filters.json
Re: comment I'm about to add to [facebook.com/10158228152624342](https://facebook.com/10158228152624342)
> filters.json: add 'configurable_actions' to 20200713 'covid'

- hideable.json
> hideable.json: add 356 'Post Header: Founding Member Badge'

- hideable.json
hideable.json: add 2020082501 'Post: Post Insights / Post Boosting block'
hideable.json: add 2020082502 'Post: View Insights'
hideable.json: add 2020082503 'Post: People Reached'
> post boosting hiders

- hideable.json
hideable.json: add 2020091401 'Left Col: Campus'
hideable.json: add 2020091402 'Left Col: Climate Science Information Center'
> 2 new Explore items

- hideable.json
> hideable.json: add 2020100101 'Above Group Feed: Watch Our Recent Facebook Communities Summit Keynote'

- hideable.json
hideable.json: add 2020121301 'Group: About box'
hideable.json: add 2020121302 'Group: Popular Topics box'
hideable.json: add 2020121303 'Group: Recent Media box'
hideable.json: add 2020121304 'Group: Events box'
(failed to get a picture of 'Events', and now can't find a group with an event to show me!)
> annoyo blobs at the top of a group

- tweaks.json
Raising this so I can quick commit it; but waiting for @siffegh to prepare an announcement (or tell me to...)
> tweaks.json: update 7 'Remove Status Background Colors' to support 2020 new layout

- hideable.json
Derivation:
```
html[sfx_url='/friends'] -- restrict to just /friends page
.btwxx1t3.gs1a9yip -- flex-direction:row, align-items:stretch
> .cbu4d94t -- flex-direction:column
[role=navigation] = the People You May Know bar on the left side of the Friends page
```
> hideable.json: add 2020123101 'Friends page: People You May Know'

- hideable.json
2021010401 'Left Column: Friends'
2021010402 'Left Column: Groups'
2021010403 'Left Column: Marketplace'
2021010404 'Left Column: Watch'
2021010405 'Left Column: Ad Center'
2021010406 'Left Column: Ads Manager'
2021010407 'Left Column: Blood Donations'
2021010408 'Left Column: Buy and Sell Groups'
2021010409 'Left Column: Campus'
2021010410 'Left Column: Climate Science Information Center'
2021010411 'Left Column: Community Help'
2021010412 'Left Column: COVID-19 Information Center'
2021010413 'Left Column: Events'
2021010414 'Left Column: Facebook Pay'
2021010415 'Left Column: Favorites'
2021010416 'Left Column: Friend Lists'
2021010417 'Left Column: Fundraisers'
2021010418 'Left Column: Games'
2021010419 'Left Column: Gaming Video'
2021010420 'Left Column: Jobs'
2021010421 'Left Column: …
> hideable.json: add new layout left col hiders; right col Sponsored

- hideable.json
> hideable.json: add 2021010601 'Left Column: Crisis Response'

- hideable.json
hideable.json: add 2021011001 'Left Rail: Resources'
hideable.json: add 2021011002 'Left Rail: Ad Center (Page admin)'
hideable.json: add 2021011003 'Left Rail: Pages (Page admin)'
Resources:
Ad Center, Pages: see fb.com/456879129051303
> 3 more left rail items

- tweaks.json
These are common characteristics of the lower left corner ephemeral notifications (2021-03-22):
```
- - <div class="lfi1tu6t poy2od1o re5koujm kavbgo14">
- - ................... .poy2od1o { position: fixed; }
- - - <ul class="p7hjln8o">
- - ........... .p7hjln8o { list-style: none; }
- - - - <li class="pedkr2u6 g3zh7qmp pc15xi3s r5qslco7 ilcmz9jb q9uorilb pmk7jnqg j9ispegn" style="bottom: 0px;">
- - ............. .pedkr2u6 { opacity: 1; }
- - ................................................. .ilcmz9jb { transition-timing-function: var(--fds-animation-enter-exit-in); }
- - ................................................................... .pmk7jnqg { position: absolute; }
- - ............................................................................ .j9ispegn { left: 0; }
```
Next in is …
> tweaks.json: update 3 'Hide Notification Bubble' for latest layout changes

- filters.json
This will fix Sponsored filtering for people whose posts are being correctly selected.  Details elsewhere.
> 28 'Sponsored' add new layout matcher

- hideable.json
hideable.json: add 2021041101 'News Feed: Remember Password prompt'
hideable.json: add 2021041102 'News Feed: Take A Survey prompt'
hideable.json: add 2021041103 'Left Rail: News'
> 2 top-of-feed + 1 left rail items

- hideable.json
> hideable.json: add 2021042301 'Post: Get Vaccine Info'

- hideable.json
- handle full URLs
- adapt format to match more recent entries
- (don't add trailing slash where previously absent)
> hideable.json: update 202008230[123] 'Header: Watch/Marketplace/Groups':

- hideable.json
- formerly 'Right Rail: Sponsored item'
- I figured out how to successfully span the ad(s) *and* their header!
> hideable.json: rename and update 2021010501i 'Right Rail: Sponsored'

- hideable.json
- remove 'Menu' from the name of 2021042902 "Header: 'Create' menu"
- add 2021042906 "Header: 'Menu' menu"
> hideable.json: split 'Menu' button from 'Create'

- hideable.json
also modernize titles of 202008230[456] as:
- 2020082304 "Header: 'Watch' button"
- 2020082305 "Header: 'Marketplace' button"
- 2020082306 "Header: 'Groups' button"
(and thinking of changing all to 'Top Bar: whatever'...)
> hideable.json: add 2021050101 "Header: 'News' button"

- hideable.json
> hideable.json: add 2021051301 'Left Rail: Emotional Health'

- hideable.json
hideable.json: add 2021051501 'Right Rail: Birthdays'
hideable.json: add 2021051502 'Right Rail: Friend Requests (list)'
hideable.json: add 2021051503 'Right Rail: Friend Requests (entire block)'
> 3 new (and high demand) right col hideables

- hideable.json
'Group Right Col: Recent Files'
'Group Right Col: Rooms'
'Header: 'Events' button'
> Group Right Col additions + Header 'Events' button

- hideable.json
> hideable.json: fix 2021042905 'Header: 'Pages' button' targeting

- hideable.json
- better selector
- parent anchor which creates a hider that doesn't scroll with the page body
> hideable.json: fix 2021032201 'Groups Feed Right Col: ad to join groups'

- hideable.json
> hideable.json: add 2021071101 'Post: FB pay-for-exposure ad'

- hideable.json
> hideable.json: add 2021071801 'Left Rail: Create Ad'

- hideable.json
hideable.json: add 2021091801 'Post: Climate Science'
hideable.json: make 2021042301 'Post: Covid Info' slightly less specific / more robust
> post-internal junk nuggets

- hideable.json
hideable.json: fix 2021092205 'Games Right Col: Instant Games' false match
hideable.json: add 2021092210 'Games Right Col: Recommended Games'
> One more game ad

- filters.json
> filters.json: add 'Because you viewed' to 2021082601 'Hide Suggested Posts'

- hideable.json
> hideable.json: add 2021101502 'Post: Recommend a thing'

- hideable.json
> hideable.json: add 2021103101 'Post: see groups like ...'

- hideable.json
hideable.json: focus 2020082301 'News Feed: Stories' on News Feed only
hideable.json: add 2020103102 'Profile: Add to Story'
The old hider hides 'Edit Profile' & '...' buttons on own Profile page.
> Split 'News Feed: Stories' into two separate hiders

- hideable.json
> Left Rail items + News Feed: Create Story

- hideable.json
Wheee, so much fun.  At least this will give me a *real* test of hider
subscription updating...
> hideable.json: 2020082303 'Right Rail (entire block)' avoid 'theater' comment area

- hideable.json
Fix by adding '?': News Feed left rail item is '.../marketplace/?ref=bookmark'.
> hideable.json: 2021010403 'Left Rail: Marketplace' avoid /marketplace left rail items

- filters.json
- add 'Based on your recent'
- try to collect suggested group name for the post-hidden message
- sort alphabetically to make future updates easier
> filters.json: update 2021082601 'Hide Suggested Posts'

- hideable.json
Right Rail: Suggested Groups
Right Rail: Group conversations
> Two right rail items

- hideable.json
Definition is conjectural, doing live test with user
> hideable.json: add 2021121501 'Right Rail: Live Video'

- hideable.json
```
.poy2od1o.i09qtzwb.n7fi1qx3 .pmk7jnqg ul.cbu4d94t ~ .t1p8iaqh
.poy2od1o {position:fixed;}          [ something positioned
.i09qtzwb {bottom:0;}                  in lower
.n7fi1qx3 {right:0;}                   right corner of screen ]
.pmk7jnqg {position:absolute;}       [ position:absolute component of it ]
ul.cbu4d94t {flex-direction:column;} [ vertical column of stuff (chat heads) ]
~
.t1p8iaqh {flex-basis:inherit;}      [ thing after that ]
```
> hideable.json: add 2021121502 'New chat message'

- filters.json
- hideable.json
Post: Find volunteers (fb.com/688761989196348 -- not sure if this actually addresses her original cases of 'Create opportunity' and 'Select nonprofit'...)
Post: Subscribe Now (fb.com/4656144041136976) -- not tested -- reporter was unable to reproduce the original example or any other
Post: Let more people see (fb.com/684702542935626)
Post: Create subgroup (ran into this myself, no post)
=====
github says this will also merge a filters change, but command line diffing shows no change -- I guess I will clean up after merge, if something does happen
> four internal turdlets FB like to embed in posts

- hideable.json
'Suggested Games' tiles now point to either /gaming/blah or /games/blah
> hideable.json: update 2021061601 'Right Rail: Play Games' for new URL

- hideable.json
> add 'Favorites: A New Way ...', fix 'News Feed: Rooms'

- hideable.json
2 sloppy errors in committing it...
> hideable.json: fix 2022022501 'News Feed: Facebook ad discount'

- hideable.json
> hideable.json: add 2022031401 'Business Page Inbox: Personalized Suggestions'

- filters.json
filters.json: add 'Events you may like' to 2021082601 'Suggested'
filters.json: add variant names 'omicron', 'delta variant', 'deltacron' to 20200713 'Covid'
> small additions to 'Suggestion' & 'Covid' filters

- hideable.json
hideable.json: update 2021042301 'Post: Covid Info' for changed post structure
hideable.json: update 2021091801 'Post: Climate Science' for changed post structure
> Update two in-post hiders for a change in post structure

- hideable.json
New classes used:
.qensuy8j {border-bottom-color:var(--always-dark-overlay)}
-- the button's border
.tiyi1ipj {align-self:baseline}
.py34i1dx {color:var(--blue-link)}
-- position and color of the blue 'Create room' button text itself
> hideable.json: fix 2020082302 'News Feed: Rooms' when no friendheads in the box

- filters.json
filters.json: add 'Semantle' to 2022031701 'Wordle'
filters.json: fix 'Nerdle' to catch game# like other clauses do
> more Wordloid games

- hideable.json
hideable.json: add 2022051200 'Global Panel: Your Profile'
hideable.json: add 2022051201 'Global Panel: Home (Facebook)'
hideable.json: add 2022051202 'Global Panel: Search Facebook'
hideable.json: add 2022051203 'Global Panel: Notifications'
hideable.json: add 2022051204 'Global Panel: Messenger'
hideable.json: add 2022051205 'Global Panel: Menu'
hideable.json: add 2022051206 'Global Panel: Watch'
hideable.json: add 2022051207 'Global Panel: Groups'
hideable.json: add 2022051208 'Global Panel: List of groups'
> Hideables for the new side-panel ('Global Panel') buttons

- hideable.json
> hideable.json: add 2022060401 'Post: Comment Suggestions'

- hideable.json
> hideable.json: add 2022072801 'Post: Emoji Suggestions'

- hideable.json
Previous parent is sometimes zero-width...
> hideable.json: fix parent for 2022060401, 2022060402, 2022072801 'Post: %s Suggestions'

- hideable.json
> hideable.json: add 2022081001 'Profile: People You May Know' (not a fakepost)

- hideable.json
hideable.json: update 8 'Header' hiders not to need gibberish classes
hideable.json: update 50 'Left Rail' hiders not to need gibberish classes
> fix 58 popular hiders to not need gibberish classes (making them work again)

- hideable.json
> hideable.json: add 2022110200 'Group: Engage with members'

- filters.json
New match for a.width:100%.display:inline[href*=/reel/] based on user-supplied HTML in fb.com/960749485330929
> filters.json: update Reels part of 2021082601 'Suggested'

- hideable.json
> hideable.json: add 2023012801 'Left Rail: Ray-Ban Stories'

- hideable.json
Rolling this out as a test hider; if it works, many more will come...
> hideable.json: add 2023013001 "Left Rail 'animated': Watch"

- hideable.json
> hideable.json: add 202303240 "Header: 'Feeds' button"

- tweaks.json
Putting this out as a test tweak, to be added to FIXES-TWEAK if it works
> tweaks.json: add 2023052701 'missing datestamps'

- hideable.json
> 'Profile: Create with avatar' + ancient cleanup

- hideable.json
hideable.json: add 2023081700 'Left Rail: Meta Quest'
hideable.json: add 2023081701 'Left Rail: Feeds'
> Left Rail: Feeds & Meta Quest

- hideable.json
> Hideables for not-logged-in screen + 'make a post' media buttons

- hideable.json
URL per fb.com/1116808856391657;  no screenshot, I believe the poster's read of the URL.
(plus whitespace fixes)
> hideable.json: add 2023101301 'Left Rail: Dating'

- filters.json
> filters.json: update 2021082601 'Suggested' to handle longer group names

- filters.json
> filters.json: add 'Connections' game to 2022031701 'Wordle'

- filters.json
I'd like to change all clauses, but let's start small
> filters.json: find 'Connections' in ${content} not ${all_content} in 2022031701 'Wordle'

- filters.json
filters.json: add latent 'show_note' settings to 5 'Create Game/App Tabs'
filters.json: make 5 'Create Game/App Tabs' actions configurable
> improve usability of 'Create Game/App Tabs' filter

- filters.json
> filters.json: add 'Murdle' to 2022031701 'Wordle'

- hideable.json
> hideable.json: add 2025041801 'Left Rail: Meta AI'

- hideable.json
> hideable.json: add 2025062601 'Chat Sidebar: Contacts: Meta AI bot'
